package com.example.util

object Constants {

    const val MIN_USERNAME_LENGTH = 4
    const val MAX_USERNAME_LENGTH = 16
    const val MIN_PASSWORD_LENGTH = 8
    const val MAX_PASSWORD_LENGTH = 32
    const val MIN_CHAT_GROUP_NAME_LENGTH = 6
    const val MAX_CHAT_GROUP_NAME_LENGTH = 16

    const val TYPE_JOIN_CHAT_REQUEST = "TYPE_JOIN_CHAT_REQUEST"
    const val TYPE_JOIN_GROUP_REQUEST = "TYPE_JOIN_GROUP_REQUEST"
    const val TYPE_NORMAL_CHAT_MESSAGE = "TYPE_NORMAL_CHAT_MESSAGE"
    const val TYPE_CHAT_GROUP_MESSAGE = "TYPE_CHAT_GROUP_MESSAGE"
    const val TYPE_JOIN_MY_CHATS_REQUEST = "TYPE_JOIN_MY_CHATS_REQUEST"
    const val TYPE_RECENT_CHATS = "TYPE_RECENT_CHATS"
    const val TYPE_MESSAGES_FOR_THIS_CHAT = "TYPE_MESSAGES_FOR_THIS_CHAT"
    const val TYPE_MESSAGES_FOR_THIS_GROUP = "TYPE_MESSAGES_FOR_THIS_GROUP"
}